# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
#all:

all:
  ckeditor:
    basePath: '/js/ckeditor/'

#  dakEvents:
#    pingOnUpdate:
#      someWordpressSite:
#        url: 'http://someaddress/xmlrpc.php'
#        type: xmlrpc-wp
#        user: admin
#        pass: test
#        methodName: someXmlRPCmethodName
#      someSitePing:
#        type: ping
#        url: 'http://someaddress/request.php'
