generator:
  class: sfDoctrineGenerator
  param:
    model_class:           arranger
    theme:                 customAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          arranger
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        max_per_page: 10
        sort: [name, asc]
        title: Arranger management
        display: [=name, created_at, updated_at]
      filter:  ~
      form:    ~
      edit:
        title: Editing arranger "%%name%%"
      new:
        title: Arranger creation
