generator:
  class: sfDoctrineGenerator
  param:
    model_class:           location
    theme:                 customAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          location
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Locations
        display: [=name]
        # It's not possible to sort by name by the very nature of nested sets
        sort: [lft, asc]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
