generator:
  class: sfDoctrineGenerator
  param:
    model_class:           locationReservation
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          location_reservation
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        statusString: { label: "Status" }
      list:
        display: [=title, statusString, arranger, location, activatedRequirements, updated_at]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
