generator:
  class: sfDoctrineGenerator
  param:
    model_class:           category
    theme:                 customAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          category
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: 
        _edit:
          credentials: [admin]
        _delete:
          credentials: [admin]
      fields:  ~
      list:
        max_per_page: 10
        sort: [name, asc]
        display: [ =name, created_at, updated_at ]
        title: Category management
      filter:  ~
      form:    ~
      edit:
        title: Editing category "%%name%%"
      new:
        title: New category
